### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by warren-sadler** [DoctorDecisions/evidence-care-service-proposal#2]
Make consideration for including rate-limiting as a middleware for service-template. 

> This is primarily a placeholder issue, will refine with requirements later.

**Comment by jclangst** [comment]
Rate limiting will be handled at the service mesh layer so should be abstracted away from each service's scope of concerns.

**Comment by warren-sadler** [comment]
That's a good point @jclangst, closing this issue.
