### ISSUE TITLE
Service Interchange Format

### ISSUE THREAD

**Issue by warren-sadler** [DoctorDecisions/evidence-care-service-proposal#4]
- Initial ideas: [ProtoBuffs](https://developers.google.com/protocol-buffers)
> This is primarily a placeholder issue, will refine with requirements later.

**Comment by jclangst** [comment]
I think this might be a premature optimization as it will add significant development overhead in my experience.

**Comment by warren-sadler** [comment]
This issue is in response to a question asked by @rmacy, I can concede that it does indeed add additional complexity. We can shelve this issue and look to examine the question post alpha release of the service-proposal.
